import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Background, BackgroundVariant, ConnectionLineType, Controls, ReactFlow, applyNodeChanges, type Connection, type Edge, type Node, type NodeChange } from "@xyflow/react";
import { passageLinks, setSocketTarget, socketDirectives } from "../core/story-html";
import type { Point, Story } from "../core/types";
import { ChipNode, ChipSection, RoutedEdge, StageLane, Wire, nearestHandles } from "./MapElements";

const nodeTypes={passage:ChipNode,group:ChipSection,stageLane:StageLane},edgeTypes={routed:RoutedEdge,wire:Wire};
const stageOf=(text:string)=>text.match(/^\s*@stage\s+(.+?)\s*$/im)?.[1].trim()||"Unstaged";
const stageColors=["#65d48b","#73a8e8","#c18aed","#e29b67","#dbc766","#65c9c0"];
const removeLinkAt=(text:string,index:number)=>{let found=-1;return text.split(/\r?\n/).map(line=>{if(/^\s*(?:\/Socket\b|Continue\s*:)/i.test(line))return line;return line.replace(/\[\[([^\]]+)\]\]/g,match=>++found===index?"":match)}).join("\n").replace(/\n{3,}/g,"\n\n")};
const clearSocketAt=(text:string,index:number)=>{let found=-1;return text.split(/\r?\n/).map(line=>{if(!/^\s*(?:\/Socket\b|Continue\s*:)/i.test(line))return line;found++;if(found!==index)return line;const socket=line.trim().match(/^\/Socket(?:\s+([^\-]+?))?(?:\s*->.*)?$/i);return socket?`/Socket ${socket[1]?.trim()||"Continue"}`:""}).filter((line,index,lines)=>line||lines[index-1]!=="").join("\n")};
export function BlueprintToolbar({onFit}:{onFit():void}){return <div className="blueprint-toolbar blueprint-toolbar-icons" aria-label="Blueprint controls"><span className="board-light" title="Microchip board"><i/></span><button onClick={onFit} title="Fit all chips in view" aria-label="Fit board">⌗</button></div>}

export function BlueprintEditor({story,onChange,onOpenPassage}:{story:Story;onChange(story:Story):void;onOpenPassage(id:string):void}){
  const [collapsed,setCollapsed]=useState<Set<string>>(()=>new Set());
  const arrangedStages=useRef("");
  const toggle=useCallback((id:string)=>setCollapsed(old=>{const next=new Set(old);next.has(id)?next.delete(id):next.add(id);return next}),[]);
  const stageLayout=useMemo(()=>{const stages=[...new Set(story.passages.map(p=>stageOf(p.text)))];const positions=new Map<string,Point>(),lanes:Node[]=[];stages.forEach((stage,stageIndex)=>{const passages=story.passages.filter(p=>stageOf(p.text)===stage),x=stageIndex*260;passages.forEach((p,index)=>positions.set(p.pid,{x:x+58,y:70+index*142}));lanes.push({id:`stage-${stageIndex}`,type:"stageLane",position:{x,y:20},data:{stage,color:stageColors[stageIndex%stageColors.length]},width:220,height:Math.max(180,passages.length*142+50),zIndex:-20,selectable:false,draggable:false,style:{width:220,height:Math.max(180,passages.length*142+50)}})});return {positions,lanes,signature:story.passages.map(p=>`${p.pid}:${stageOf(p.text)}`).join("|")}},[story.passages]);
  useEffect(()=>{if(arrangedStages.current===stageLayout.signature)return;arrangedStages.current=stageLayout.signature;onChange({...story,passages:story.passages.map(p=>({...p,position:stageLayout.positions.get(p.pid)||p.position}))})},[stageLayout,onChange,story]);
  const passageNodes=useCallback((s:Story):Node[]=>[...stageLayout.lanes,...s.metadata.groups.map(g=>({id:`group-${g.id}`,type:"group",position:g.position,data:{...g,collapsed:collapsed.has(`group-${g.id}`),onToggle:()=>toggle(`group-${g.id}`),onColor:(color:string)=>onChange({...s,metadata:{...s.metadata,groups:s.metadata.groups.map(x=>x.id===g.id?{...x,color}:x)}})},width:g.width,height:collapsed.has(`group-${g.id}`)?54:g.height,zIndex:-10,style:{width:g.width,height:collapsed.has(`group-${g.id}`)?54:g.height}})),...s.passages.map(p=>({id:p.pid,type:"passage",position:p.position,data:{label:p.name,start:p.pid===s.storyAttributes.startnode,sockets:s.metadata.sockets.filter(x=>x.passageId===p.pid),hasTerminalContinue:/^\s*Continue\s*:\s*\[\[[^\]]+\]\]\s*$/i.test(p.text.trim().split(/\r?\n/).at(-1)||""),collapsed:collapsed.has(p.pid),onToggle:()=>toggle(p.pid)},zIndex:5}))],[collapsed,onChange,stageLayout.lanes,toggle]);
  const [nodes,setNodes]=useState<Node[]>(()=>passageNodes(story));useEffect(()=>setNodes(passageNodes(story)),[story,passageNodes]);
  const positions=useMemo(()=>new Map(nodes.map(n=>[n.id,{x:n.position.x+(n.measured?.width||220)/2,y:n.position.y+(n.measured?.height||100)/2}])),[nodes]);
  const edges=useMemo<Edge[]>(()=>{const byName=new Map(story.passages.map(p=>[p.name,p.pid])),result:Edge[]=[];story.passages.forEach(p=>{passageLinks(p.text).forEach((target,index)=>{const targetId=byName.get(target);if(!targetId)return;const id=`link-${p.pid}-${targetId}-${index}`,route=story.metadata.routes.find(r=>r.id===id),handles=nearestHandles();const update=(points:Point[])=>onChange({...story,metadata:{...story.metadata,routes:[...story.metadata.routes.filter(r=>r.id!==id),{id,source:p.pid,target:targetId,points}]}});result.push({id,source:p.pid,target:targetId,...handles,type:route?.points.length?"routed":"wire",data:route?{...route,update,color:route.color||"#78d99d",powered:true,kind:"link",index}:{color:"#78d99d",powered:true,kind:"link",index}})});socketDirectives(p.text).forEach((socket,index)=>{if(!socket.target)return;const targetId=byName.get(socket.target);if(!targetId)return;const meta=story.metadata.sockets.find(s=>s.passageId===p.pid&&s.id===socket.id),id=`socket-${p.pid}-${index}`,route=story.metadata.routes.find(r=>r.id===id),update=(points:Point[])=>onChange({...story,metadata:{...story.metadata,routes:[...story.metadata.routes.filter(r=>r.id!==id),{id,source:p.pid,target:targetId,sourceSocket:socket.id,points,color:meta?.color}]}});result.push({id,source:p.pid,target:targetId,sourceHandle:`socket-${index}`,targetHandle:"in-left",type:route?.points.length?"routed":"wire",data:{...(route||{id,source:p.pid,target:targetId,points:[]}),color:meta?.color,powered:true,kind:"socket",index,update}})});});return result},[story,onChange]);
  const onNodesChange=(changes:NodeChange[])=>{setNodes(current=>applyNodeChanges(changes,current));if(changes.some(c=>c.type==="position"&&c.dragging===false)||changes.some(c=>c.type==="dimensions"&&c.resizing===false))setNodes(current=>{onChange({...story,passages:story.passages.map(p=>{const n=current.find(x=>x.id===p.pid);return n?{...p,position:n.position}:p}),metadata:{...story.metadata,groups:story.metadata.groups.map(g=>{const n=current.find(x=>x.id===`group-${g.id}`);return n?{...g,position:n.position,width:n.measured?.width||n.width||g.width,height:n.measured?.height||n.height||g.height}:g})}});return current})};
  const onConnect=(c:Connection)=>{if(!c.source||!c.target)return;const source=story.passages.find(p=>p.pid===c.source),target=story.passages.find(p=>p.pid===c.target);if(!source||!target)return;const socketIndex=c.sourceHandle?.match(/^socket-(\d+)$/)?.[1];onChange({...story,passages:story.passages.map(p=>p.pid!==source.pid?p:{...p,text:socketIndex!==undefined?setSocketTarget(p.text,Number(socketIndex),target.name):`${p.text.trimEnd()}\n\nContinue: [[${target.name}]]`})})};
  const addRoutePoint=(e:Edge)=>{const source=positions.get(e.source),target=positions.get(e.target);if(!source||!target)return;const point={x:(source.x+target.x)/2,y:(source.y+target.y)/2};onChange({...story,metadata:{...story.metadata,routes:[...story.metadata.routes.filter(r=>r.id!==e.id),{id:e.id,source:e.source,target:e.target,points:[...(story.metadata.routes.find(r=>r.id===e.id)?.points||[]),point]}]}})};
  const deleteNodes=(deleted:Node[])=>{const passageIds=new Set(deleted.filter(n=>n.type==="passage").map(n=>n.id)),deletedNames=new Set(story.passages.filter(p=>passageIds.has(p.pid)).map(p=>p.name)),groupIds=new Set(deleted.filter(n=>n.type==="group").map(n=>n.id.replace(/^group-/,"")));const invalidate=(text:string)=>text.split(/\r?\n/).map(line=>{const target=line.match(/\[\[([^\]]*)\]\]/)?.[1]?.trim();if(!target||!deletedNames.has(target))return line;if(/^\s*\/Socket\b/i.test(line))return line.replace(/\s*->\s*\[\[[^\]]*\]\]\s*$/i,"");if(/^\s*Continue\s*:/i.test(line))return line.replace(/\[\[[^\]]*\]\]/,"[[]]");return line.replace(/\[\[[^\]]*\]\]/,"")}).join("\n");onChange({...story,passages:story.passages.filter(p=>!passageIds.has(p.pid)).map(p=>({...p,text:invalidate(p.text)})),metadata:{...story.metadata,groups:story.metadata.groups.filter(g=>!groupIds.has(g.id)),routes:story.metadata.routes.filter(r=>!passageIds.has(r.source)&&!passageIds.has(r.target)),sockets:story.metadata.sockets.filter(s=>!passageIds.has(s.passageId)&&(!s.target||!deletedNames.has(s.target)))}})};
  const deleteEdges=(deleted:Edge[])=>{const bySource=new Map<string,Edge[]>();deleted.forEach(edge=>bySource.set(edge.source,[...(bySource.get(edge.source)||[]),edge]));onChange({...story,passages:story.passages.map(p=>{const sourceEdges=bySource.get(p.pid);if(!sourceEdges)return p;let text=p.text;sourceEdges.sort((a,b)=>Number((b.data as {index?:number})?.index||0)-Number((a.data as {index?:number})?.index||0)).forEach(edge=>{const data=edge.data as {kind?:string;index?:number};text=data.kind==="socket"?clearSocketAt(text,data.index||0):removeLinkAt(text,data.index||0)});return {...p,text}}),metadata:{...story.metadata,routes:story.metadata.routes.filter(route=>!deleted.some(edge=>edge.id===route.id))}})};
  return <section className="map full blueprint-board"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} edgeTypes={edgeTypes} defaultEdgeOptions={{zIndex:0}} onNodesChange={onNodesChange} onNodesDelete={deleteNodes} onEdgesDelete={deleteEdges} onConnect={onConnect} onNodeDoubleClick={(_,n)=>n.type==="passage"&&onOpenPassage(n.id)} onEdgeDoubleClick={(_,e)=>addRoutePoint(e)} fitView minZoom={.18} maxZoom={2.2} colorMode="dark" connectionLineType={ConnectionLineType.Bezier} connectionLineStyle={{stroke:"#9df2b9",strokeWidth:3,filter:"drop-shadow(0 0 6px #6cff9d)"}} selectNodesOnDrag panOnScroll selectionOnDrag><Background variant={BackgroundVariant.Lines} gap={44} size={1} color="#244632"/><Background variant={BackgroundVariant.Dots} gap={22} size={1} color="#396147"/><Controls/><BlueprintToolbar onFit={()=>document.querySelector<HTMLButtonElement>(".react-flow__controls-fitview")?.click()}/></ReactFlow></section>;
}
